---
- name: Check if maven is installed
  command: mvn --version
  ignore_errors: True
  register: mvn_check

- name: Create /opt directory
  file: path=/opt state=directory
  sudo: True
  when: mvn_check|failed

- name: Download Maven3
  get_url: dest=/opt/maven3.tar.gz url=http://apache.proserve.nl/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  sudo: True
  when: mvn_check|failed

- name: Unpack Maven3
  action: command creates=/opt/maven chdir=/opt tar zxvf /opt/maven3.tar.gz
  sudo: True
  when: mvn_check|failed

- name: Create Maven3 directory link
  file: path=/opt/maven src=/opt/apache-maven-3.3.9 state=link
  sudo: True
  when: mvn_check|failed

- name: Set mvn link
  action: command update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 1
  sudo: True
  when: mvn_check|failed

