---
- name: install python setup tools
  yum: name=python-setuptools state=installed
  sudo: True
  tags: supervisor

- name: install supervisor with easy_install
  shell: easy_install supervisor
  sudo: True
  tags: supervisor

- name: configure supervisord
  shell: /usr/bin/echo_supervisord_conf > {{supervisor.config.file}}
  sudo: True
  tags: supervisor

- name: backup default configuration
  shell: cp {{supervisor.config.file}} {{supervisor.config.default}} creates={{supervisor.config.default}}
  sudo: True
  tags: supervisor

- name: prepare necessary directories
  file: path={{item}} state=directory recurse=yes
  with_items:
    - "{{supervisor.log.dir}}"
    - "{{supervisor.config.dir}}"
    - "{{supervisor.runtime.dir}}"
  sudo: True
  tags: supervisor

- name: configure runtime and log
  ini_file: dest={{supervisor.config.file}}
            section={{item.section}}
            option={{item.option}}
            value={{item.value}}
  with_items:
      - { section: unix_http_server, option: file, value: "{{supervisor.runtime.dir}}/{{supervisor.runtime.socket}}" }
      - { section: supervisorctl, option: serverurl, value: "unix://{{supervisor.runtime.dir}}/{{supervisor.runtime.socket}}" }
      - { section: supervisord, option: pidfile, value: "{{supervisor.runtime.dir}}/{{supervisor.runtime.pidfile}}" }
      - { section: supervisord, option: nodaemon, value: "{{supervisor.runtime.nodaemon}}" }
      - { section: supervisord, option: logfile, value: "{{supervisor.log.dir}}/{{supervisor.log.file}}" }
      - { section: supervisord, option: loglevel, value: "{{supervisor.log.level}}" }
  sudo: True
  tags: supervisor

- name: tell supervisor to include relative configurations directory
  ini_file: dest={{supervisor.config.file}}
            section=include
            option=files
            value={{supervisor.config.dir}}/*.ini
            state=present
  sudo: True
  tags: supervisor

- name: configure web ui status checking server
  ini_file: dest={{supervisor.config.dir}}/{{supervisor.http.file}}
            section=inet_http_server
            option={{item.key}}
            value={{item.value}}
            state=present
  with_dict: supervisor.http
  sudo: True
  tags:
      - supervisor-http
      - supervisor

- name: add programs
  ini_file: dest={{supervisor.config.dir}}/{{item.0.file}}
            section="program:{{item.0.name}}"
            option="{{item.1.keys()[0]}}"
            value="{{item.1.values()[0]}}"
            state=present
  with_subelements:
      - supervisor.programs
      - values
  sudo: True
  when: supervisor.programs is defined
  tags:
      - supervisor-programs
      - supervisor

- name: make sure supervisord is running and up-to-date
  shell: echo Magic...
  notify:
    - run supervisord
    - reread supervisord config
    - add programs to process group
    - change supervisord programs states
  sudo: True
  tags:
    - run-supervisord  
    - supervisor
